repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.10
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    - id: mypy

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.248'
    hooks:
      - id: ruff
