repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [lsprotocol, pygls, pytest]
        args: [src, tests]
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.12.2'
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: test
        additional_dependencies: [uv]
        name: run tests
        language: python
        types: [python]
        pass_filenames: false
        entry: uv run -m pytest
