name: Test
on:
  - push
  - pull_request

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12","3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: CI Checks
        run: |
          python -m pip install --upgrade pip uv
          uv sync
          uv run -m coverage run -m pytest tests
          uv run -m mypy src tests
          uv run -m ruff
