name: Test
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10","3.11"]

    steps:
    - name: Run Tests
      run: |
        python -m pip install --upgrade pip
        make test
